/**
 * Trace correlation driver.
 *
 * Implements the Bridge-side trace primitive used by worker issue #70:
 * every RPC call gets a stable trace ID that links the worker decision,
 * the bridge dispatch, and the resulting evidence bundle.
 *
 * Design:
 *   - Trace IDs are generated by the worker when possible (passed via
 *     `params._traceId` or RPC context). When absent, the bridge mints
 *     a fresh ID so every call still has one.
 *   - We keep a bounded ring buffer of recent (traceId → command record)
 *     so `bridge.evidenceBundle` can attach the most recent N commands
 *     without depending on the service worker staying alive forever.
 */

const MAX_RECORDS = 256

const records = []
let sequence = 0

/**
 * RFC 4122 v4-ish ID. We don't need cryptographic guarantees here, only
 * uniqueness within a process. Falls back to Math.random when crypto is
 * unavailable (test harness in node).
 */
export function newTraceId(prefix = "trace") {
  sequence += 1
  const rand = Math.random().toString(16).slice(2, 10)
  const ts = Date.now().toString(36)
  return `${prefix}-${ts}-${sequence.toString(36)}-${rand}`
}

/**
 * Pick a trace ID from RPC params/context, or mint a new one.
 */
export function ensureTraceId({ params, context } = {}) {
  const fromParams = params && typeof params._traceId === "string" ? params._traceId : null
  const fromCtx = context && typeof context.traceId === "string" ? context.traceId : null
  const id = fromParams || fromCtx || newTraceId()
  return id
}

/**
 * Record a tool dispatch outcome. Bounded ring buffer.
 */
export function recordDispatch({ traceId, method, params, transport, status, durationMs, error }) {
  const entry = {
    traceId,
    method,
    transport: transport || "unknown",
    status,
    startedAt: Date.now() - (durationMs || 0),
    durationMs: durationMs || 0,
    error: error || null,
    paramsPreview: previewParams(params),
  }
  records.push(entry)
  if (records.length > MAX_RECORDS) records.splice(0, records.length - MAX_RECORDS)
  return entry
}

/**
 * Return recent dispatch records, optionally filtered by trace ID.
 */
export function getRecentDispatches({ traceId, limit = 50 } = {}) {
  const filtered = traceId ? records.filter((r) => r.traceId === traceId) : records
  const start = Math.max(0, filtered.length - limit)
  return filtered.slice(start)
}

/**
 * Reset internal state. Test-only.
 */
export function _resetForTests() {
  records.length = 0
  sequence = 0
}

function previewParams(params) {
  if (params == null) return null
  try {
    const json = JSON.stringify(params)
    return json.length > 512 ? `${json.slice(0, 509)}...` : json
  } catch {
    return "<unserializable>"
  }
}
